### ISSUE TITLE
Developer, what do you want?

### ISSUE THREAD

**Issue by Openwrtfunboy** [amnezia-vpn/amneziawg-linux-kernel-module#15]
Ensure that you have source repositories configured for APT - run vi /etc/apt/sources.list and make sure that there is at least one line starting with deb-src is present and uncommented.

What you want me to do? I don't understand at all. Can you provide command or something that will help? I added "deb-src" to bottom and now it shows erros while executing any apt commands

**Comment by Openwrtfunboy** [comment]
sudo apt-get install -y amneziawg
Чтение списков пакетов… Готово
Построение дерева зависимостей… Готово
Чтение информации о состоянии… Готово         
Уже установлен пакет amneziawg самой новой версии (1.0.20210914-0~202407150831+e42813c~ubuntu22.04.1).
Обновлено 0 пакетов, установлено 0 новых пакетов, для удаления отмечено 0 пакетов, и 2 пакетов не обновлено.
Установлено или удалено не до конца 2 пакетов.
После данной операции объём занятого дискового пространства возрастёт на 0 B.
Настраивается пакет amneziawg-dkms (1.0.0-0~202408051835+c981738~ubuntu22.04.1) …
Removing old amneziawg-1.0.0 DKMS files...
Deleting module amneziawg-1.0.0 completely from the DKMS tree.
Loading new amneziawg-1.0.0 DKMS files...
Building for 5.15.0-118-generic
Building initial module for 5.15.0-118-generic
E: Вы должны заполнить sources.list, поместив туда URI источников пакетов с исходным кодом
ls: невозможно получить доступ к '*/': Нет такого файла или каталога
ERROR: Cannot create report: [Errno 17] File exists: '/var/crash/amneziawg-dkms.0.crash'
Error! Bad return status for module build on kernel: 5.15.0-118-generic (x86_64)
Consult /var/lib/dkms/amneziawg/1.0.0/build/make.log for more information.
dpkg: ошибка при обработке пакета amneziawg-dkms (--configure):
 подпроцесс из пакета amneziawg-dkms установлен сценарий post-installation возвратил код ошибки 10
dpkg: зависимости пакетов не позволяют настроить пакет amneziawg:
 amneziawg зависит от amneziawg-dkms (>= 0.0.20200121-2) | amneziawg-modules (>= 0.0.20191219), однако:
  Пакет amneziawg-dkms пока не настроен.
  Пакет amneziawg-modules не установлен.

dpkg: ошибка при обработке пакета amneziawg (--configure):
 проблемы зависимостей — оставляем не настроенным
Отчёт apport не записан, так как сообщение об ошибке указывает на повторную ошибку от предыдущего отказа.
                        При обработке следующих пакетов произошли ошибки:
 amneziawg-dkms
 amneziawg
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by Openwrtfunboy** [comment]
при том соус пакет присутствует

Пол:11 https://ppa.launchpadcontent.net/amnezia/ppa/ubuntu focal InRelease [18,0 kB]
Сущ:12 http://archive.ubuntu.com/ubuntu jammy-updates InRelease                 
Пол:13 https://ppa.launchpadcontent.net/amnezia/ppa/ubuntu focal/main Sources [1 128 B]

**Comment by Openwrtfunboy** [comment]
а и хрен с ним

**Comment by vitidev** [comment]
Я пропустил шаг  echo "net.ipv4.ip_forward = 1" > /etc/sysctl.d/00-amnezia.conf
и была такая же ошибка. Потом не пропустил и оно сработало. А может просто совпадение.

**Comment by GubernievS** [comment]
In my file is not have  deb-src

cat /etc/apt/sources.list
# Ubuntu sources have moved to the /etc/apt/sources.list.d/ubuntu.sources
# file, which uses the deb822 format. Use deb822-formatted .sources files
# to manage package sources in the /etc/apt/sources.list.d/ directory.
# See the sources.list(5) manual page for details.

what to do?

**Comment by ja49619** [comment]
same error, any ideas?

**Comment by Openwrtfunboy** [comment]
The fix is manually copy sources of wireguard drivers as I remember to corresponding folder. So in the end I have working amnezia WG on my OWRT x86.
