### ISSUE TITLE
Could not be compiled.

### ISSUE THREAD

**Issue by vztmaster** [amnezia-vpn/amneziawg-linux-kernel-module#2]
Could not be compiled.

error: ‘struct sk_buff’ has no member named ‘headers’; did you mean ‘head’?
   82 |         memset(&skb->headers, 0, sizeof(skb->headers));
      |                      ^~~~~~~
      |                      head
/home/adm01/awg-linux-kernel-module/src/queueing.h:82:46: error: ‘struct sk_buff’ has no member named ‘headers’; did you mean ‘head’?
   82 |         memset(&skb->headers, 0, sizeof(skb->headers));
      |                                              ^~~~~~~
      |                                              head
make[2]: *** [scripts/Makefile.build:297: /home/adm01/awg-linux-kernel-module/src/main.o] Error 1
make[1]: *** [Makefile:1909: /home/adm01/awg-linux-kernel-module/src] Error 2
make: *** [Makefile:26: module] Error 2

**Comment by leninalive** [comment]
Please try compilation from `master` branch once again, this should be working now.
