### ISSUE TITLE
/tmp too small for kernel sources

### ISSUE THREAD

**Issue by Igor-N** [amnezia-vpn/amneziawg-linux-kernel-module#31]
Hi! I'm got a problem with amneziawg on fresh kernel 6.11.0-8 (Ubuntu 24.10). PRE_BUILD script prepare-sources.sh  uses PREFIX=${AWG_TEMP_DIR:-/tmp} for bulding workdir path and downloading kernel sources into workdir. But tempfs /tmp as inmemory fs probably too small for kernel sources. Maybe it's better to use /var/tmp instead of /tmp as default prefix for workdir?

As temporary workout it's possible to use  AWG_TEMP_DIR var like  AWG_TEMP_DIR=/var/tmp apt install amneziawg, but it's easy to forget it for all sequential apt upgrades. 

Thanks for amneziawg!

**Comment by leninalive** [comment]
> As temporary workout it's possible to use AWG_TEMP_DIR var like AWG_TEMP_DIR=/var/tmp apt install amneziawg, but it's easy to forget it for all sequential apt upgrades.

It is not needed for sub sequential apt upgrades, and this issue is documented in README file.
