### ISSUE TITLE
Broken dependencies for Ubuntu Mantic

### ISSUE THREAD

**Issue by ddkedr** [amnezia-vpn/amneziawg-linux-kernel-module#4]
I'm getting a dependency error, while installing amneziawg on Ubuntu Mantic:
```bash
The following packages have unmet dependencies:
 amneziawg : Depends: amneziawg-dkms (>= 0.0.20200121-2) but it is not installable or
                      amneziawg-modules (>= 0.0.20191219) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

This happens with Ubuntu Mantic repository only (and maybe some others). After changing a repository to Ubuntu Jammy, all the dependencies can be found successfully.

We can see no amneziawg-linux-kmod package in Ubuntu Mantic repository on Launchpad:

https://launchpad.net/~amnezia/+ppa-packages

or https://ppa.launchpadcontent.net/amnezia/ppa/ubuntu/pool/main/a/amneziawg-linux-kmod/

So the question is: Can I install a Jammy amneziawg-dkms and amneziawg-modules packages on a Mantic system?

**Comment by batazor** [comment]
+1

**Comment by rendleks** [comment]
+1, the same for me

**Comment by leninalive** [comment]
For some reason Launchpad doesn't support Mantic for build recipes, but we sure you could use any other distribution freely.

Closing this issue for now, feel free to open it if you have further comments.
