### ISSUE TITLE
Non-compatible with new versions of Linux stable kernel

### ISSUE THREAD

**Issue by MaxVanch** [amnezia-vpn/amneziawg-linux-kernel-module#53]
Hi! I tried to compile it in Arch Linux with kernel 6.11.8-arch1-2, but it's not compatible with it, but it's compatible with 6.6.62-1-lts, so because of this I temporary (I hope) changed kernel to linux-lts.
[make.log](https://github.com/user-attachments/files/17780992/make.log)

**Comment by leninalive** [comment]
Just compiled on Arch Linux with 6.12.1-arch1 kernel and headers.
