### ISSUE TITLE
when SKB is non-linear?

### ISSUE THREAD

**Issue by korzhyc** [amnezia-vpn/amneziawg-linux-kernel-module#7]
### Current behavior:
  Packets from clients using S1>0 are silently dropped by the server.
  (Which may be caused by NIC driver page data location.)

### Expected behavior:
  Correctly handle non-linear SKB.
  If no support is planned, then throw a warning into the console and do not try to process such packets.

**For example...**
[001-fixup-amneziawg.patch](https://github.com/user-attachments/files/15897949/001-fixup-amneziawg.patch)

**Comment by leninalive** [comment]
Thanks a lot for your issue, we have fixed it in latest release!
